# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
 - stage: Build
   jobs:
     - job: BuildJob
       steps:
         - bash: echo Running Buildjob
 - stage: Dev
   jobs:
     - deployment: DevDeployJob
       environment : Dev
       strategy: 
           runOnce:
             deploy:
               steps: 
               - bash : echo Running - DevDeployJob
 - stage: QA
   jobs:
     - deployment: QADeployJob
       environment : QA
       strategy: 
           runOnce:
            deploy:
              steps:
                - bash: echo Running - QADeployJob